"""Embeds the Technical Architecture Report (Deliverable 2) directly into
README.md, so the full report is visible on the repo's landing page instead
of requiring a click into a subfolder file.

`report/technical_architecture_report.md` remains the single source of
truth - it's what `report/build_pdf.py` renders and what a human should
edit. This script regenerates the copy embedded in README.md between two
HTML comment markers every time it runs (wired into `make report`), so the
two never drift out of sync from a forgotten hand-edit in one place only.
"""

from __future__ import annotations

import re
from pathlib import Path

REPORT_DIR = Path(__file__).parent
REPO_ROOT = REPORT_DIR.parent
SOURCE = REPORT_DIR / "technical_architecture_report.md"
README = REPO_ROOT / "README.md"

BEGIN_MARKER = (
    "<!-- BEGIN: EMBEDDED TECHNICAL ARCHITECTURE REPORT - auto-generated by "
    "report/build_readme.py from report/technical_architecture_report.md. "
    "Do not hand-edit this section; edit the source file and run `make report`. -->"
)
END_MARKER = "<!-- END: EMBEDDED TECHNICAL ARCHITECTURE REPORT -->"


def demote_headers(md_text: str) -> str:
    """# -> ##, ## -> ###, ### -> #### - so the report nests one level
    under whatever heading wraps it in README.md instead of colliding with
    README's own top-level structure. Safe here specifically because no
    fenced-code-block line in the source starts with `#` (checked)."""
    return re.sub(r"^(#{1,3})(\s)", r"#\1\2", md_text, flags=re.MULTILINE)


def fix_relative_image_paths(md_text: str) -> str:
    # Every image reference in the source resolves relative to report/
    # (correct when GitHub renders technical_architecture_report.md
    # directly); embedded in the repo-root README.md they all need the
    # report/ prefix to resolve to the same files. Matches any
    # `(diagrams/...)` reference, not one hardcoded filename, since the
    # report embeds multiple generated charts, not just the AWS diagram.
    return re.sub(r"\(diagrams/", "(report/diagrams/", md_text)


def build_readme_section() -> None:
    embedded = fix_relative_image_paths(demote_headers(SOURCE.read_text()))

    readme_text = README.read_text()
    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(readme_text):
        raise RuntimeError(
            f"README.md is missing the embedded-report markers - expected both:\n{BEGIN_MARKER}\n{END_MARKER}"
        )
    replacement = f"{BEGIN_MARKER}\n\n{embedded}\n{END_MARKER}"
    README.write_text(pattern.sub(replacement, readme_text))
    print(f"README.md's embedded report section regenerated from {SOURCE}")


if __name__ == "__main__":
    build_readme_section()
